#!/bin/bash
export VERSIONABLE_SNAPSHOT=false
export VERSIONABLE_NAME="Google Test"
export VERSIONABLE_VERSION_PRIMARY="1"
export VERSIONABLE_VERSION_SECONDARY="12"
export VERSIONABLE_VERSION_PATCH="1"
